import { theme as antTheme } from 'antd';

/**
 * Maps SyncDoc CSS semantic tokens → Ant Design theme config.
 * Token values reference CSS variables so theme switches stay in sync.
 */
export function getAntdTheme(mode = 'light') {
  const isDark = mode === 'dark';

  return {
    cssVar: { key: 'syncdoc' },
    algorithm: isDark ? antTheme.darkAlgorithm : antTheme.defaultAlgorithm,
    token: {
      colorPrimary: 'var(--gdocs-primary, #1a73e8)',
      colorPrimaryHover: '#1765cc',
      colorPrimaryActive: '#185abc',
      colorSuccess: '#10b981',
      colorWarning: '#f59e0b',
      colorError: '#ef4444',
      colorInfo: '#3b82f6',
      colorBgBase: 'var(--preset-bg-base)',
      colorBgContainer: 'var(--preset-bg-elevated)',
      colorBgElevated: 'var(--preset-bg-elevated)',
      colorBgLayout: 'var(--preset-bg-base)',
      colorText: 'var(--preset-text-primary)',
      colorTextSecondary: 'var(--preset-text-secondary)',
      colorTextTertiary: 'var(--preset-text-muted)',
      colorTextQuaternary: 'var(--preset-text-disabled)',
      colorBorder: 'var(--preset-border-default)',
      colorBorderSecondary: 'var(--preset-border-subtle)',
      colorLink: 'var(--link-color)',
      colorLinkHover: 'var(--link-color-hover)',
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 6,
      fontFamily: 'var(--font-family-sans)',
      fontSize: 16,
      controlHeight: 40,
      lineWidth: 1,
      lineType: 'solid',
    },
    components: {
      Button: {
        colorPrimary: 'var(--btn-primary-bg)',
        colorPrimaryHover: 'var(--btn-primary-bg-hover)',
        colorPrimaryActive: 'var(--btn-primary-bg-active)',
        primaryColor: 'var(--btn-primary-text)',
        defaultBg: 'var(--btn-default-bg)',
        defaultColor: 'var(--btn-default-text)',
        defaultBorderColor: 'var(--btn-default-border)',
        defaultHoverBg: 'var(--btn-default-bg-hover)',
        defaultHoverColor: 'var(--btn-default-text)',
        defaultHoverBorderColor: 'var(--btn-default-border)',
        defaultActiveBg: 'var(--btn-default-bg-active)',
        colorText: 'var(--btn-ghost-text)',
        colorTextHover: 'var(--btn-ghost-text-hover)',
        colorBgTextHover: 'var(--btn-ghost-bg-hover)',
        colorError: 'var(--btn-danger-bg)',
        colorErrorHover: 'var(--btn-danger-bg-hover)',
        colorErrorActive: 'var(--btn-danger-bg-active)',
        colorBgContainerDisabled: 'var(--btn-disabled-bg)',
        colorTextDisabled: 'var(--btn-disabled-text)',
        borderColorDisabled: 'var(--btn-disabled-border)',
        borderRadius: 8,
      },
      Input: {
        colorBgContainer: 'var(--input-bg)',
        colorText: 'var(--input-text)',
        colorTextPlaceholder: 'var(--input-text-placeholder)',
        colorTextDisabled: 'var(--input-text-disabled)',
        colorBorder: 'var(--input-border)',
        hoverBorderColor: 'var(--input-border-hover)',
        activeBorderColor: 'var(--input-border-focus)',
        colorError: 'var(--input-border-error)',
        colorBgContainerDisabled: 'var(--input-bg-disabled)',
        activeShadow: 'var(--input-shadow-focus)',
        borderRadius: 8,
      },
      Select: {
        colorBgContainer: 'var(--select-bg)',
        colorBorder: 'var(--select-border)',
        hoverBorderColor: 'var(--select-border-hover)',
        optionSelectedBg: 'var(--select-option-bg-selected)',
        optionActiveBg: 'var(--select-option-bg-hover)',
        borderRadius: 8,
      },
      Card: {
        colorBgContainer: 'var(--card-bg)',
        colorBorderSecondary: 'var(--card-border)',
        boxShadowTertiary: 'var(--card-shadow)',
        headerBg: 'var(--card-bg)',
        colorTextHeading: 'var(--card-header-text)',
        borderRadiusLG: 12,
      },
      Layout: {
        bodyBg: 'var(--app-content-bg)',
        headerBg: 'var(--header-bg)',
        headerColor: 'var(--header-text)',
        siderBg: 'var(--sidebar-bg)',
        triggerBg: 'var(--sidebar-trigger-bg)',
        triggerColor: 'var(--sidebar-trigger-text)',
      },
      Menu: {
        itemBg: 'transparent',
        itemColor: 'var(--sidebar-text)',
        itemHoverBg: 'var(--sidebar-item-bg-hover)',
        itemHoverColor: 'var(--preset-text-primary)',
        itemSelectedBg: 'var(--sidebar-item-bg-active)',
        itemSelectedColor: 'var(--sidebar-text-active)',
        activeBarBorderWidth: 0,
      },
      Drawer: {
        colorBgElevated: 'var(--drawer-bg)',
        colorSplit: 'var(--drawer-border)',
      },
      Modal: {
        contentBg: 'var(--drawer-bg)',
        headerBg: 'var(--drawer-bg)',
      },
      Tag: {
        defaultBg: 'var(--tag-default-bg)',
        defaultColor: 'var(--tag-default-text)',
        colorSuccess: 'var(--tag-success-text)',
        colorSuccessBg: 'var(--tag-success-bg)',
        colorWarning: 'var(--tag-warning-text)',
        colorWarningBg: 'var(--tag-warning-bg)',
        colorError: 'var(--tag-error-text)',
        colorErrorBg: 'var(--tag-error-bg)',
      },
      Divider: {
        colorSplit: 'var(--divider-color)',
      },
      Typography: {
        colorText: 'var(--preset-text-primary)',
        colorTextSecondary: 'var(--preset-text-secondary)',
        colorTextDescription: 'var(--preset-text-muted)',
        colorLink: 'var(--link-color)',
        colorLinkHover: 'var(--link-color-hover)',
      },
      Form: {
        labelColor: 'var(--preset-text-primary)',
      },
      Alert: {
        colorInfoBg: 'var(--color-info-50)',
        colorInfoBorder: '#bfdbfe',
        colorSuccessBg: 'var(--color-success-50)',
        colorSuccessBorder: '#a7f3d0',
        colorWarningBg: 'var(--color-warning-50)',
        colorWarningBorder: '#fde68a',
        colorErrorBg: 'var(--color-error-50)',
        colorErrorBorder: '#fecaca',
      },
      Dropdown: {
        colorBgElevated: 'var(--preset-bg-elevated)',
      },
      Tooltip: {
        colorBgSpotlight: 'var(--preset-bg-inverse)',
        colorTextLightSolid: 'var(--preset-text-inverse)',
      },
    },
  };
}
